version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: svg_color
      DATABASE_USERNAME: svg_color_u
      DATABASE_PASSWORD: qYte7L(-Pa
      DATABASE_SSL: 'false'
      PORT: 8005
    volumes:
      - ./app:/srv/app
    ports:
      - '8005:8005'
    depends_on:
      - mysql

  mysql:
    image: mysql
    # command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
    #   MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: svg_color
      MYSQL_USER: svg_color_u
      MYSQL_PASSWORD: qYte7L(-Pa
