version: '3'
services:
  strapi:
    image: strapi/strapi
    volumes:
      - .:/srv/app
    ports:
      - '8005:8005'
    depends_on:
      - mysql

  mysql:
    image: mysql
    # command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql:/var/lib/mysql
